#!/usr/bin/env Rscript

# ================================================================
# SCRIPT 02: Filter Reference Regions + QC Plots for Consensus
#
# Pipeline: comethyl WGBS consensus analysis
#
# PURPOSE
#   Reads the candidate region table generated from consensus Script 01,
#   filters regions using minimum coverage and methylation SD
#   thresholds, and generates QC plots for:
#     1) unfiltered regions
#     2) filtered regions
#     3) combined comparison of unfiltered vs filtered
#
# REQUIRED INPUTS
#   --project_root  : root directory of the analysis project
#   --dataset_label : reference dataset label
#   --input_regions : path to Regions.txt generated by consensus Script 01
#
# OPTIONAL INPUTS
#   --cov_min       : minimum region-level coverage threshold
#                     [default = 4]
#   --meth_sd       : minimum methylation SD threshold
#                     [default = 0.08]
#   --base_size     : base font size for combined QC plot
#                     [default = 22]
#   --bins          : number of histogram bins
#                     [default = 40]
#   --max_q         : upper quantile trimming for plotting
#                     [default = 0.99]
#   --width         : width of combined QC plot in inches
#                     [default = 20]
#   --height        : height of combined QC plot in inches
#                     [default = 10]
#
# OUTPUTS
#   <project_root>/comethyl_output/consensus/02_reference_region_filter/<dataset_label>/<input_label>/covMin<cov>_methSD<meth>/
#       Filtered_Regions.txt
#       Filtered_Regions.rds
#       RegionStats_UNFILTERED.pdf
#       RegionStats_FILTERED.pdf
#       RegionStats_FilterEffect_COMBINED.pdf
#       run_parameters.txt
#       sessionInfo.txt
#
# NOTES
#   - input_label is automatically derived from the parent folder of
#     --input_regions, for example:
#         input_regions = .../01_reference_filter_regions/Baseline/cov3_75pct/Regions.txt
#         input_label   = cov3_75pct
#   - The combined QC plot uses the unfiltered regions to define
#     quantile trimming so the filtered and unfiltered distributions
#     remain comparable.
#   - This step should be run only on the reference dataset.
#   - The resulting Filtered_Regions.txt is the canonical region
#     definition for downstream consensus analysis.

# Example

# Rscript /quobyte/lasallegrp/projects/wgbs_growell_comethylation_analysis/tests/demo/scripts/comethyl_scripts/consensus/02_filter_reference_regions_consensus.R \
#   --project_root /quobyte/lasallegrp/projects/wgbs_growell_comethylation_analysis/tests/demo \
#   --dataset_label Baseline \
#   --input_regions /quobyte/lasallegrp/projects/wgbs_growell_comethylation_analysis/tests/demo/comethyl_output/consensus/01_reference_filter_regions/Baseline/cov3_75pct/Regions.txt \
#   --covMin 4 \
#   --methSD 0.08
# ================================================================
message("Starting ✓")

suppressPackageStartupMessages({
  library(optparse)
  library(comethyl)
  library(data.table)
  library(ggplot2)
  library(scales)
  library(reshape2)
  library(grid)
})

# ------------------------------------------------------------
# 1. Parse command-line arguments
# ------------------------------------------------------------

option_list <- list(
  make_option("--project_root", type = "character",
              help = "Root directory of the project"),
  make_option("--dataset_label", type = "character",
              help = "Reference dataset label (e.g. Baseline)"),
  make_option("--input_regions", type = "character",
              help = "Path to Regions.txt from consensus Script 01"),
  make_option("--cov_min", type = "integer", default = 4,
              help = "Minimum region coverage threshold [default = 4]"),
  make_option("--meth_sd", type = "double", default = 0.08,
              help = "Minimum methylation SD threshold [default = 0.08]"),
  make_option("--base_size", type = "double", default = 22,
              help = "Base font size for combined QC plot [default = 22]"),
  make_option("--bins", type = "integer", default = 40,
              help = "Histogram bins [default = 40]"),
  make_option("--max_q", type = "double", default = 0.99,
              help = "Upper quantile trimming for plotting [default = 0.99]"),
  make_option("--width", type = "double", default = 20,
              help = "Combined plot width in inches [default = 20]"),
  make_option("--height", type = "double", default = 10,
              help = "Combined plot height in inches [default = 10]")
)

opt <- parse_args(OptionParser(option_list = option_list))

# ------------------------------------------------------------
# 2. Validate inputs
# ------------------------------------------------------------

if (is.null(opt$project_root)) stop("--project_root is required")
if (is.null(opt$dataset_label)) stop("--dataset_label is required")
if (is.null(opt$input_regions)) stop("--input_regions is required")

opt$dataset_label <- trimws(opt$dataset_label)

if (!nzchar(opt$dataset_label)) {
  stop("--dataset_label cannot be empty")
}
if (!dir.exists(opt$project_root)) {
  stop("Project root does not exist: ", opt$project_root)
}
if (!file.exists(opt$input_regions)) {
  stop("Input Regions.txt not found: ", opt$input_regions)
}
if (opt$cov_min < 1) {
  stop("--cov_min must be >= 1")
}
if (opt$meth_sd < 0) {
  stop("--meth_sd must be >= 0")
}
if (opt$max_q <= 0 || opt$max_q > 1) {
  stop("--max_q must be > 0 and <= 1")
}
if (opt$bins < 1) {
  stop("--bins must be >= 1")
}

# ------------------------------------------------------------
# 3. Define output directories automatically
# ------------------------------------------------------------
# Example:
#   input file from:
#     .../01_reference_filter_regions/Baseline/cov3_75pct/Regions.txt
#   output folder:
#     .../02_reference_region_filter/Baseline/cov3_75pct/covMin4_methSD0p08/

pipeline_root <- file.path(opt$project_root, "comethyl_output", "consensus")
step_dir <- file.path(pipeline_root, "02_reference_region_filter")

input_label <- basename(dirname(opt$input_regions))

meth_sd_label <- gsub("\\.", "p", as.character(opt$meth_sd))
version_label <- paste0("covMin", opt$cov_min, "_methSD", meth_sd_label)

out_dir <- file.path(step_dir, opt$dataset_label, input_label, version_label)
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

message("Output directory: ", out_dir)

# ------------------------------------------------------------
# 4. Define output files
# ------------------------------------------------------------

filtered_regions_path <- file.path(out_dir, "Filtered_Regions.txt")
filtered_regions_rds  <- file.path(out_dir, "Filtered_Regions.rds")
pdf_unf_only <- file.path(out_dir, "RegionStats_UNFILTERED.pdf")
pdf_flt_only <- file.path(out_dir, "RegionStats_FILTERED.pdf")
pdf_combined_big <- file.path(out_dir, "RegionStats_FilterEffect_COMBINED.pdf")

# ------------------------------------------------------------
# 5. Load unfiltered regions
# ------------------------------------------------------------

regions_unf <- data.table::fread(opt$input_regions, data.table = FALSE)

required_cols <- c("RegionID", "width", "n", "covMin", "covMean", "methMean", "methSD")
missing_cols <- setdiff(required_cols, colnames(regions_unf))

if (length(missing_cols) > 0) {
  stop(
    "Missing required columns in input regions: ",
    paste(missing_cols, collapse = ", ")
  )
}

if (anyDuplicated(regions_unf$RegionID)) {
  dup_ids <- unique(regions_unf$RegionID[duplicated(regions_unf$RegionID)])
  stop("Duplicate RegionID values found in unfiltered regions. Example: ",
       paste(head(dup_ids, 10), collapse = ", "))
}

message("Loaded unfiltered regions: ", nrow(regions_unf))

# ------------------------------------------------------------
# 6. Filter regions
# ------------------------------------------------------------

regions_filt <- filterRegions(
  regions_unf,
  covMin = opt$cov_min,
  methSD = opt$meth_sd,
  file = filtered_regions_path
)

if (nrow(regions_filt) == 0) {
  stop("No regions remained after filtering.")
}

saveRDS(regions_filt, filtered_regions_rds)

message("Filtered regions: ", nrow(regions_filt))
message("Saved filtered regions: ", filtered_regions_path)

# ------------------------------------------------------------
# 7. Separate QC plots
# ------------------------------------------------------------

plotRegionStats(
  regions_unf,
  maxQuantile = opt$max_q,
  file = pdf_unf_only
)

plotRegionStats(
  regions_filt,
  maxQuantile = opt$max_q,
  file = pdf_flt_only
)

message("Saved separate plots:")
message(" - ", pdf_unf_only)
message(" - ", pdf_flt_only)

# ------------------------------------------------------------
# 8. Combined QC plot: unfiltered vs filtered
# ------------------------------------------------------------

plotRegionStatsCompare2 <- function(unfiltered, filtered,
                                    bins = 40,
                                    alpha = 0.85,
                                    nBreaks = 4,
                                    maxQuantile = 0.99,
                                    covMin_cutoff = NULL,
                                    methSD_cutoff = NULL,
                                    covMean_cutoff = NULL,
                                    base_size = 22,
                                    save = TRUE,
                                    file = "RegionStats_FilterEffect_COMBINED.pdf",
                                    width = 18,
                                    height = 10,
                                    verbose = TRUE) {

  if (verbose) message("[plotRegionStatsCompare2] Building combined QC plot")

  variables <- c("width", "n", "covMin", "covMean", "methMean", "methSD")

  unf <- unfiltered
  fil <- filtered

  unf$status <- "Unfiltered"
  fil$status <- "Filtered"

  unf <- unf[, c("RegionID", variables, "status")]
  fil <- fil[, c("RegionID", variables, "status")]

  regions <- rbind(unf, fil)

  # Quantile trimming is based on the unfiltered distribution so that
  # filtered and unfiltered panels share comparable x-axis limits.
  if (maxQuantile < 1) {
    for (v in c("width", "n", "covMin", "covMean")) {
      q <- stats::quantile(unf[[v]], probs = maxQuantile, na.rm = TRUE)
      regions[[v]][regions[[v]] >= q] <- NA
    }
  }

  regions_long <- reshape2::melt(
    regions,
    id.vars = c("RegionID", "status"),
    measure.vars = variables,
    variable.name = "variable",
    value.name = "value"
  )

  medians <- aggregate(
    value ~ status + variable,
    data = regions_long,
    FUN = function(x) stats::median(x, na.rm = TRUE)
  )

  thr <- data.frame()
  if (!is.null(covMin_cutoff)) {
    thr <- rbind(thr, data.frame(variable = "covMin", x = covMin_cutoff))
  }
  if (!is.null(covMean_cutoff)) {
    thr <- rbind(thr, data.frame(variable = "covMean", x = covMean_cutoff))
  }
  if (!is.null(methSD_cutoff)) {
    thr <- rbind(thr, data.frame(variable = "methSD", x = methSD_cutoff))
  }

  gg <- ggplot(regions_long, aes(x = value, fill = status, color = status)) +
    geom_histogram(bins = bins, position = "identity", alpha = alpha, na.rm = TRUE) +
    geom_vline(
      data = medians,
      aes(xintercept = value, color = status),
      linewidth = 1.2,
      show.legend = FALSE
    ) +
    facet_grid(status ~ variable, scales = "free_x", switch = "x") +
    scale_x_continuous(breaks = breaks_pretty(n = nBreaks)) +
    scale_y_continuous(expand = expansion(mult = c(0.01, 0.05))) +
    theme_bw(base_size = base_size) +
    theme(
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title = element_blank(),
      panel.grid = element_blank(),
      strip.background = element_blank(),
      strip.placement = "outside",
      panel.spacing = unit(0.7, "lines"),
      legend.position = "top",
      legend.title = element_blank(),
      strip.text.x = element_text(size = base_size),
      strip.text.y = element_text(size = base_size)
    )

  if (nrow(thr) > 0) {
    gg <- gg +
      geom_vline(
        data = thr,
        aes(xintercept = x),
        linetype = "dashed",
        linewidth = 1.1,
        color = "black",
        inherit.aes = FALSE
      )
  }

  if (save) {
    if (verbose) message("[plotRegionStatsCompare2] Saving: ", file)
    ggsave(
      filename = file,
      plot = gg,
      dpi = 600,
      width = width,
      height = height,
      units = "in"
    )
  }

  return(gg)
}

plotRegionStatsCompare2(
  unfiltered = regions_unf,
  filtered = regions_filt,
  bins = opt$bins,
  maxQuantile = opt$max_q,
  covMin_cutoff = opt$cov_min,
  methSD_cutoff = opt$meth_sd,
  base_size = opt$base_size,
  file = pdf_combined_big,
  width = opt$width,
  height = opt$height
)

message("Saved combined plot: ", pdf_combined_big)

# ------------------------------------------------------------
# 9. Save run parameters for reproducibility
# ------------------------------------------------------------

writeLines(
  c(
    paste("project_root:", opt$project_root),
    paste("dataset_label:", opt$dataset_label),
    paste("input_regions:", opt$input_regions),
    paste("input_label:", input_label),
    paste("cov_min:", opt$cov_min),
    paste("meth_sd:", opt$meth_sd),
    paste("base_size:", opt$base_size),
    paste("bins:", opt$bins),
    paste("max_q:", opt$max_q),
    paste("width:", opt$width),
    paste("height:", opt$height),
    paste("n_regions_before:", nrow(regions_unf)),
    paste("n_regions_after:", nrow(regions_filt)),
    paste("output_dir:", out_dir),
    paste("date:", as.character(Sys.time()))
  ),
  con = file.path(out_dir, "run_parameters.txt")
)

writeLines(
  capture.output(sessionInfo()),
  con = file.path(out_dir, "sessionInfo.txt")
)

# ------------------------------------------------------------
# 10. Summary
# ------------------------------------------------------------

message("✓ Consensus Script 02 complete: reference region filtering and QC plots complete")
message("Output folder: ", out_dir)
message("Regions after filtering: ", nrow(regions_filt))