#!/usr/bin/env Rscript

# ================================================================
# SCRIPT 05b: Filter Shared Complete Regions Across Timepoints
#
# Pipeline: comethyl WGBS consensus analysis
#
# PURPOSE
#   Loads region-level methylation matrices from two or three
#   timepoint datasets (generated by consensus Scripts 03 and/or 05),
#   identifies regions that are complete (no NAs) across ALL provided
#   timepoints, subsets each matrix to the shared complete region set,
#   and saves the filtered matrices for downstream PC diagnostics
#   and consensus module analysis.
#
#   This step is necessary because sva::num.sv() and SVD-based PCA
#   cannot handle missing values. Imputation with 0 is inappropriate
#   for WGBS methylation data where NAs reflect insufficient coverage.
#   Removing regions with NAs in any timepoint ensures that all
#   downstream analyses use a consistent, complete set of regions.
#
# REQUIRED INPUTS
#   --project_root    : root directory of the analysis project
#   --dataset1_label  : label for timepoint/dataset 1
#   --dataset1_meth   : path to Region_Methylation.rds for dataset 1
#   --dataset2_label  : label for timepoint/dataset 2
#   --dataset2_meth   : path to Region_Methylation.rds for dataset 2
#
# OPTIONAL INPUTS
#   --dataset3_label  : label for timepoint/dataset 3
#   --dataset3_meth   : path to Region_Methylation.rds for dataset 3
#
# OUTPUTS
#   <project_root>/comethyl_output/consensus/05b_shared_complete_regions/
#       shared_complete_regionIDs.rds
#       shared_complete_regionIDs.txt
#       <dataset1_label>_Methylation_complete.rds
#       <dataset2_label>_Methylation_complete.rds
#       <dataset3_label>_Methylation_complete.rds  (if dataset 3 provided)
#       region_coverage_summary.txt
#       run_parameters.txt
#       sessionInfo.txt
#
# NOTES
#   - All input matrices must have RegionIDs as rownames.
#   - Only regions present AND complete in all provided datasets
#     are retained. Regions missing from any dataset are excluded.
#   - The filtered matrices saved here should be used as --input_meth
#     in consensus Script 06 (PC diagnostics) in place of the
#     original Region_Methylation.rds files.
# 

# Example
# Rscript /path/to/scripts/consensus/05b_filter_shared_complete_regions_consensus.R \
#   --project_root /quobyte/lasallegrp/projects/wgbs_growell_comethylation_analysis/tests/demo \
#   --dataset1_label Baseline \
#   --dataset1_meth /quobyte/.../03_region_methylation/Baseline/cov3_75pct/covMin4_methSD0p05/Region_Methylation.rds \
#   --dataset2_label 36-38wk \
#   --dataset2_meth /quobyte/.../03_region_methylation/36-38wk/36-38wk/covMin4_methSD0p05/Region_Methylation.rds \
#   --dataset3_label Postpartum \
#   --dataset3_meth /quobyte/.../03_region_methylation/Postpartum/Postpartum/covMin4_methSD0p05/Region_Methylation.rds
# ================================================================
message("Starting \u2713")

suppressPackageStartupMessages({
  library(optparse)
})

# ------------------------------------------------------------
# 1. Parse command-line arguments
# ------------------------------------------------------------

option_list <- list(
  make_option("--project_root", type = "character",
              help = "Root directory of the project"),

  make_option("--dataset1_label", type = "character",
              help = "Label for dataset/timepoint 1"),
  make_option("--dataset1_meth", type = "character",
              help = "Path to Region_Methylation.rds for dataset 1"),

  make_option("--dataset2_label", type = "character",
              help = "Label for dataset/timepoint 2"),
  make_option("--dataset2_meth", type = "character",
              help = "Path to Region_Methylation.rds for dataset 2"),

  make_option("--dataset3_label", type = "character", default = NULL,
              help = "Label for dataset/timepoint 3 (optional)"),
  make_option("--dataset3_meth", type = "character", default = NULL,
              help = "Path to Region_Methylation.rds for dataset 3 (optional)")
)

opt <- parse_args(OptionParser(option_list = option_list))

# ------------------------------------------------------------
# 2. Validate inputs
# ------------------------------------------------------------

if (is.null(opt$project_root))   stop("--project_root is required")
if (is.null(opt$dataset1_label)) stop("--dataset1_label is required")
if (is.null(opt$dataset1_meth))  stop("--dataset1_meth is required")
if (is.null(opt$dataset2_label)) stop("--dataset2_label is required")
if (is.null(opt$dataset2_meth))  stop("--dataset2_meth is required")

if (!dir.exists(opt$project_root)) {
  stop("Project root does not exist: ", opt$project_root)
}
if (!file.exists(opt$dataset1_meth)) {
  stop("Dataset 1 methylation file not found: ", opt$dataset1_meth)
}
if (!file.exists(opt$dataset2_meth)) {
  stop("Dataset 2 methylation file not found: ", opt$dataset2_meth)
}

dataset3_provided <- !is.null(opt$dataset3_label) || !is.null(opt$dataset3_meth)

if (dataset3_provided) {
  if (is.null(opt$dataset3_label) || is.null(opt$dataset3_meth)) {
    stop("If dataset 3 is used, provide both --dataset3_label and --dataset3_meth.")
  }
  if (!file.exists(opt$dataset3_meth)) {
    stop("Dataset 3 methylation file not found: ", opt$dataset3_meth)
  }
}

# ------------------------------------------------------------
# 3. Define output directory
# ------------------------------------------------------------

pipeline_root <- file.path(opt$project_root, "comethyl_output", "consensus")
out_dir <- file.path(pipeline_root, "05b_shared_complete_regions")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

message("Output directory: ", out_dir)

# ------------------------------------------------------------
# 4. Helper: load and validate a methylation matrix
# ------------------------------------------------------------

load_meth <- function(path, label) {
  message("Loading ", label, ": ", path)
  meth <- readRDS(path)

  if (!(is.matrix(meth) || is.data.frame(meth))) {
    stop("Methylation object for ", label, " is not a matrix or data.frame.")
  }
  meth <- as.matrix(meth)

  if (!is.numeric(meth)) {
    stop("Methylation matrix for ", label, " is not numeric.")
  }
  if (nrow(meth) == 0) {
    stop("Methylation matrix for ", label, " has zero rows.")
  }
  if (is.null(rownames(meth))) {
    stop("Methylation matrix for ", label, " must have RegionIDs as rownames.")
  }
  if (anyDuplicated(rownames(meth))) {
    dup_ids <- unique(rownames(meth)[duplicated(rownames(meth))])
    stop("Duplicate rownames in methylation matrix for ", label,
         ". Example: ", paste(head(dup_ids, 10), collapse = ", "))
  }

  message("  Loaded: ", nrow(meth), " regions x ", ncol(meth), " samples")
  meth
}

# ------------------------------------------------------------
# 5. Load all methylation matrices
# ------------------------------------------------------------

meth_list <- list()
meth_list[[opt$dataset1_label]] <- load_meth(opt$dataset1_meth, opt$dataset1_label)
meth_list[[opt$dataset2_label]] <- load_meth(opt$dataset2_meth, opt$dataset2_label)

if (dataset3_provided) {
  meth_list[[opt$dataset3_label]] <- load_meth(opt$dataset3_meth, opt$dataset3_label)
}

n_datasets <- length(meth_list)
dataset_labels <- names(meth_list)

# ------------------------------------------------------------
# 6. Find regions present in all datasets
# ------------------------------------------------------------

message("Finding regions shared across all ", n_datasets, " datasets...")

all_region_ids <- lapply(meth_list, rownames)
shared_regions <- Reduce(intersect, all_region_ids)

message("Regions per dataset (before filtering):")
for (lbl in dataset_labels) {
  message("  ", lbl, ": ", nrow(meth_list[[lbl]]))
}
message("Regions shared across all datasets: ", length(shared_regions))

if (length(shared_regions) == 0) {
  stop("No regions are shared across all datasets. Check that rownames match across matrices.")
}

# ------------------------------------------------------------
# 7. Find complete regions (no NAs) across all datasets
# ------------------------------------------------------------

message("Identifying complete regions (no NAs) in each dataset...")

complete_per_dataset <- lapply(dataset_labels, function(lbl) {
  m <- meth_list[[lbl]][shared_regions, , drop = FALSE]
  complete_idx <- complete.cases(m)
  complete_ids <- rownames(m)[complete_idx]
  n_na <- sum(!complete_idx)
  message("  ", lbl, ": ", length(complete_ids), " complete | ", n_na, " with NAs")
  complete_ids
})
names(complete_per_dataset) <- dataset_labels

shared_complete_regions <- Reduce(intersect, complete_per_dataset)

message("Regions complete across ALL datasets: ", length(shared_complete_regions))

if (length(shared_complete_regions) == 0) {
  stop("No regions are complete (NA-free) across all datasets.")
}

# ------------------------------------------------------------
# 8. Subset matrices to shared complete regions
# ------------------------------------------------------------

message("Subsetting matrices to shared complete regions...")

meth_filtered <- lapply(dataset_labels, function(lbl) {
  m <- meth_list[[lbl]][shared_complete_regions, , drop = FALSE]
  message("  ", lbl, ": ", nrow(m), " regions x ", ncol(m), " samples")
  m
})
names(meth_filtered) <- dataset_labels

# ------------------------------------------------------------
# 9. Save shared region IDs
# ------------------------------------------------------------

saveRDS(shared_complete_regions,
        file.path(out_dir, "shared_complete_regionIDs.rds"))
writeLines(shared_complete_regions,
           file.path(out_dir, "shared_complete_regionIDs.txt"))

message("Saved shared complete region IDs: ", length(shared_complete_regions))

# ------------------------------------------------------------
# 10. Save filtered methylation matrices
# ------------------------------------------------------------

for (lbl in dataset_labels) {
  safe_label <- gsub("[^A-Za-z0-9._-]", "_", lbl)
  out_path <- file.path(out_dir, paste0(safe_label, "_Methylation_complete.rds"))
  saveRDS(meth_filtered[[lbl]], out_path)
  message("Saved filtered matrix for ", lbl, ": ", out_path)
}

# ------------------------------------------------------------
# 11. Save coverage summary
# ------------------------------------------------------------

summary_lines <- c(
  "Region coverage summary",
  paste("Date:", as.character(Sys.time())),
  "",
  paste("Datasets processed:", paste(dataset_labels, collapse = ", ")),
  ""
)

for (lbl in dataset_labels) {
  n_total   <- nrow(meth_list[[lbl]])
  n_shared  <- length(shared_regions)
  n_complete <- length(complete_per_dataset[[lbl]])
  n_final   <- length(shared_complete_regions)
  summary_lines <- c(
    summary_lines,
    paste0(lbl, ":"),
    paste0("  Total regions in input matrix:          ", n_total),
    paste0("  Regions shared across all datasets:     ", n_shared),
    paste0("  Complete (NA-free) regions in dataset:  ", n_complete),
    paste0("  Final shared complete regions retained: ", n_final),
    paste0("  Regions removed (NA or not shared):     ", n_total - n_final),
    ""
  )
}

writeLines(summary_lines, file.path(out_dir, "region_coverage_summary.txt"))

# ------------------------------------------------------------
# 12. Save run parameters
# ------------------------------------------------------------

run_params <- c(
  paste("project_root:", opt$project_root),
  paste("dataset1_label:", opt$dataset1_label),
  paste("dataset1_meth:", opt$dataset1_meth),
  paste("dataset2_label:", opt$dataset2_label),
  paste("dataset2_meth:", opt$dataset2_meth)
)

if (dataset3_provided) {
  run_params <- c(
    run_params,
    paste("dataset3_label:", opt$dataset3_label),
    paste("dataset3_meth:", opt$dataset3_meth)
  )
}

run_params <- c(
  run_params,
  paste("n_datasets:", n_datasets),
  paste("n_shared_regions_before_na_filter:", length(shared_regions)),
  paste("n_shared_complete_regions:", length(shared_complete_regions)),
  paste("output_dir:", out_dir),
  paste("date:", as.character(Sys.time()))
)

writeLines(run_params, con = file.path(out_dir, "run_parameters.txt"))

writeLines(
  capture.output(sessionInfo()),
  con = file.path(out_dir, "sessionInfo.txt")
)

# ------------------------------------------------------------
# 13. Summary
# ------------------------------------------------------------

message("\n\u2713 Consensus Script 05b complete: shared complete region filtering done")
message("Output folder: ", out_dir)
message("Shared complete regions retained: ", length(shared_complete_regions))
message("\nUse the following filtered matrices as --input_meth in Script 06:")
for (lbl in dataset_labels) {
  safe_label <- gsub("[^A-Za-z0-9._-]", "_", lbl)
  message("  ", lbl, ": ",
          file.path(out_dir, paste0(safe_label, "_Methylation_complete.rds")))
}